# https://help.github.com/en/categories/automating-your-workflow-with-github-actions

name: "Semantic Release"

on: # yamllint disable-line rule:truthy
    push:
        branches:
            - "([0-9])?(.{+([0-9]),x}).x"
            - "main"
            - "next"
            - "next-major"
            - "alpha"
            - "beta"

# Enable this to use the github packages
# yamllint disable-line rule:comments
#env:
#    package: "@${{ github.repository }}"
#    registry_url: "https://npm.pkg.github.com"
#    scope: "${{ github.repository_owner }}"

jobs:
    semantic-release:
        name: "Semantic Release"

        if: "github.repository != 'anolilab/node-mono-library-template'"

        runs-on: "ubuntu-latest"

        steps:
            - name: "Git checkout"
              uses: "actions/checkout@v2"
              with:
                  fetch-depth: 0
                  persist-credentials: false
              env:
                  GIT_COMMITTER_NAME: "GitHub Actions Shell"
                  GIT_AUTHOR_NAME: "GitHub Actions Shell"
                  EMAIL: "github-actions[bot]@users.noreply.github.com"

            - name: "Use Node.js 16.x"
              uses: "actions/setup-node@v2"
              with:
                  node-version: "16.x"
                  # Enable this to use the github packages
                  # registry-url: "${{ env.registry_url }}"
                  # Defaults to the user or organization that owns the workflow file
                  # scope: "@${{ env.scope }}"

            - name: "Install pnpm"
              run: "curl -f https://get.pnpm.io/v6.16.js | node - add --global pnpm@6"

            - name: "Cache .pnpm-store"
              uses: "actions/cache@v3"
              id: "pnpm-cache" # use this to check for `cache-hit` (`steps.pnpm-cache.outputs.cache-hit != 'true'`)
              with:
                  path: "~/.pnpm-store"
                  key: "${{ runner.os }}-node16.x-${{ hashFiles('**/pnpm-lock.yaml') }}"
                  restore-keys: |
                      ${{ runner.os }}-pnpm-

            - name: "Install packages"
              run: "pnpm install --frozen-lockfile"

            - name: "Build packages"
              run: "pnpm build"

            - name: "ESLint"
              run: "pnpm run lint"

            - name: "Test packages"
              run: "pnpm test:once"

            - name: "Semantic Release"
              env:
                  GITHUB_TOKEN: "${{ secrets.SEMANTIC_RELEASE_GITHUB_TOKEN }}"
                  NPM_TOKEN: "${{ secrets.NPM_AUTH_TOKEN }}"
                  GIT_AUTHOR_NAME: "github-actions-shell"
                  GIT_AUTHOR_EMAIL: "github-actions[bot]@users.noreply.github.com"
                  GIT_COMMITTER_NAME: "github-actions-shell"
                  GIT_COMMITTER_EMAIL: "github-actions[bot]@users.noreply.github.com"
              run: "pnpm multi-semantic-release"

    pnpm-lock-update:
        name: "pnpm-lock.yaml update"

        runs-on: "ubuntu-latest"

        needs: ["semantic-release"]

        steps:
            - name: "Git checkout"
              uses: "actions/checkout@v2"
              with:
                  fetch-depth: 2
                  token: "${{ secrets.SEMANTIC_RELEASE_GITHUB_TOKEN }}"
                  ref: "${{ github.ref }}"
              env:
                  GIT_COMMITTER_NAME: "GitHub Actions Shell"
                  GIT_AUTHOR_NAME: "GitHub Actions Shell"
                  EMAIL: "github-actions[bot]@users.noreply.github.com"

            - name: "Use Node.js 16.x"
              uses: "actions/setup-node@v2"
              with:
                  node-version: "16.x"
                  # Enable this to use the github packages
                  # registry-url: "${{ env.registry_url }}"
                  # Defaults to the user or organization that owns the workflow file
                  # scope: "@${{ env.scope }}"

            - name: "Install pnpm"
              run: "curl -f https://get.pnpm.io/v6.16.js | node - add --global pnpm@6"

            - name: "Update pnpm lock"
              run: "pnpm install --no-frozen-lockfile"

            - name: "Commit modified files"
              uses: "stefanzweifel/git-auto-commit-action@v4.15.4"
              with:
                  commit_message: "chore: updated pnpm-lock.yaml"
                  commit_author: "prisis <d.bannert@anolilab.de>"
                  commit_user_email: "d.bannert@anolilab.de"
                  commit_user_name: "prisis"
                  branch: "${{ github.head_ref }}"
